const BlogData = [
  {
    id: 1,
    date: "January 01, 2023",
    catgeory: "PREMIUM ",
    title: "Iberostar 70 Park Avenue",
    cover: "/images/singlepage/blog-1.jpg",
    para: "Este hotel de Nueva York se encuentra a menos de 10 minutos a pie de la estación Grand Central y de las tiendas de la Quinta Avenida. Se trata de un hotel ecológico con habitaciones equipadas con TV de pantalla plana de 42 pulgadas. Las habitaciones del Iberostar 70 Park Avenue Hotel disponen de WiFi gratuita, soporte para iPod, ropa de cama y artículos de aseo de diseño. Además, el hotel cuenta con recepción 24 horas y servicio de conserje. El hotel está a menos de 1,6 km de Times Square y del distrito de los teatros.",
    desc: "",
  },
  {
    id: 2,
    date: "January 15, 2023",
    catgeory: "PREMIUM",
    title: "1st Luxury Warehouse",
    cover: "/images/singlepage/blog-2.jpg",
    para: "Te sentirás como en casa, o incluso mejor, gracias a detalles como una ducha con efecto lluvia y una placa de cocina, además de wifi gratis y una Smart TV. Y eso por no mencionar los edredones de plumas, las toallas, los utensilios de cocina y la plancha.",
    desc: "",
  },
  {
    id: 3,
    date: "January 21, 2023",
    catgeory: "PROMEDIO",
    title: "TownePlace Suites by Marriott Miami Kendall West",
    cover: "/images/singlepage/blog-3.jpg",
    para: "Buscar un hotel en Miami puede resultar desafiante. Towneplace Suites Miami Kendall West es la mejor opción cuando viaja al sur de Florida. Nuestros amplios estudios cuentan con cocinas totalmente equipadas, televisores Smart TV, acceso WiFi gratis y una amplia estación de trabajo. El hotel ofrece gran confort para los viajeros de negocios y de placer que pueden disfrutar de un desayuno bufet con opciones calientes gratis.",
    desc: "",
  },
  {
    id: 4,
    date: "January 30, 2023",
    catgeory: "PREMIUM",
    title: "Springhill Suites Houston Intercontinental Airport",
    cover: "/images/singlepage/blog-4.jpg",
    para: "Visita el hotel SpringHill Suites by Marriott Houston Intercontinental Airport. Se trata de un hotel de suites contemporáneo ubicado a menos de 2 km del aeropuerto intercontinental de Houston (IAH). Descubre un hotel diferente y moderno con elegancia, el SpringHill Suites Houston Intercontinental Airport, que ofrece suites cómodas con minirefrigerador, horno de microondas, sala de estar, área de trabajo y conexión WiFi gratis.",
    desc: "",
  },
  {
    id: 5,
    date: "Diciembre 10, 2023",
    catgeory: "PREMIUM",
    title: "Mayfair House Hotel & Garden",
    cover: "/images/singlepage/blog-5.jpg",
    para: "Instalaciones Se puede llegar a las plantas superiores cómodamente en ascensor. Servicios como caja fuerte y oficina de cambio ayudan a proporcionar una estancia confortable. En las zonas públicas se ofrece conexión a Internet, así como Wi-Fi. En cuanto a gastronomía, el establecimiento ofrece restaurante, cafetería, bar y pub.",
    desc: "",
  },
  {
    id: 6,
    date: "Noviembre 18, 2023",
    catgeory: "PROMEDIO",
    title: "Perfect Apt Near Ucla Pool & Gym Open W Parking B3",
    cover: "/images/singlepage/blog-6.jpg",
    para: "El PERFECT Apt near UCLA POOL & GYM OPEN w Parking B3 se encuentra a 7,1 km del Getty Center y ofrece piscina al aire libre, spa y centro de bienestar y alojamiento con aire acondicionado, balcón y WiFi gratuita. También hay sauna. El alojamiento cuenta con TV de pantalla plana, baño privado con bañera, ducha y secador de pelo y cocina con lavavajillas, horno y microondas. Hay tostadora, nevera, fogones, cafetera y hervidor de agua.",
    desc: "",
  },
  {
    id: 6,
    date: "January 12, 2023",
    catgeory: "PREMIUM",
    title: "Courtyard by Marriott San Diego Mission Valley/Hotel Circle",
    cover: "/images/singlepage/blog-1.jpg",
    para: "Experimente en Courtyard San Diego Mission Valley, un hotel histórico cerca del animado Gaslamp Quarter. Visite atracciones locales como el Petco Park y el Centro de Convenciones. Organice unos eventos inolvidables en nuestro exclusivo espacio para reuniones, que incluye servicio de banquetes y servicios audiovisuales.",
    desc: "",
  },
  {
    id: 7,
    date: "January 30, 2023",
    catgeory: " PREMIUM",
    title: "Hotel and the City, Empire State Building",
    cover: "/images/singlepage/blog-4.jpg",
    para: "El Hotel and the City, Empire State Building ofrece salón compartido y WiFi gratuita y se encuentra en Nueva York, a poca distancia del Empire State Building, Macy's y Madison Square Garden. El alojamiento está equipado con aire acondicionado, cocina totalmente equipada, TV de pantalla plana y baño privado con bañera o ducha, secador de pelo y artículos de aseo gratuitos.",
    desc: "",
  },
  {
    id: 8,
    date: "January 10, 2023",
    catgeory: "PREMUIM",
    title: "Home2 Suites by Hilton Orlando International Drive South",
    cover: "/images/singlepage/blog-5.jpg",
    para: "El Home2 Suites by Hilton Orlando International Drive South, que ofrece un centro de fitness y una piscina exterior abierta todo el año, se encuentra en Orlando, Florida, a 500 metros del centro comercial Prime Outlets Orlando. Se sirve un desayuno de forma gratuita. El alojamiento está equipado con TV de pantalla plana por cable.",
    desc: "",
  },
]

export default BlogData
